#!/bin/awk -f

# The script is used to parse "typescript", which is generated by
# `script;make all;exit`. The command generates the training trace
# with specifical identifiers "[start] random", "[start] length", "[start] raw",
# "[start] margin" to separate each experiment.

BEGIN{
  count = 0
  randomF = "result-500-random.log"
  lengthF = "result-500-length.log"
  rawF = "result-500-raw.log"
  marginF = "result-500-margin.log"
}
{
  if (/start/) {
    count++
  }
  if (count == 2) {
    print > randomF
  }
  if (count == 3) {
    print > lengthF
  }
  if (count == 4) {
    print > rawF
  }
  if (count == 5) {
    print > marginF
  } 
}
END{
  printf "Parse the trace into: %s, %s  %s  %s", randomF, lengthF, rawF, marginF
}
